language: python

addons:
    apt_packages:
        - enchant
        - aspell
        - aspell-en

matrix:
  include:
    - python: "3.7"
      env: TOXENV=lint

    - python: "3.7"
      env: TOXENV=docs

    - python: "3.7"
      env: TOXENV=codecov

    - python: "3.8-dev"
      env: TOXENV=py38

    - python: "3.6"
      env: TOXENV=py36

    - python: "3.5"
      env: TOXENV=py35

    - python: "3.4"
      env: TOXENV=py34

    - python: "2.7"
      env: TOXENV=py27

    - python: "2.7"
      env: TOXENV=el7

    - python: "2.6"
      env: TOXENV=py26
      dist: trusty

    - python: "2.6"
      env: TOXENV=el6
      dist: trusty

    - python: pypy
      env: TOXENV=pypy

    - python: pypy3
      env: TOXENV=pypy3

install:
  - pip install tox

script:
  - tox
