language: python
os: linux

addons:
    apt_packages:
        - enchant
        - aspell
        - aspell-en

matrix:
  include:
    - python: 3.9
      env: TOXENV=lint

    - python: 3.9
      env: TOXENV=docs

    - python: 3.9
      env: TOXENV=codecov

    - python: 3.10-dev
      env: TOXENV=py310

    - python: 3.8
      env: TOXENV=py38

    - python: 3.7
      env: TOXENV=py37

    - python: 3.6
      env: TOXENV=py36

    - python: 3.5
      env: TOXENV=py35

    - python: 2.7
      env: TOXENV=py27

    - python: 2.7
      env: TOXENV=el7

    - python: pypy2
      env: TOXENV=pypy2

    - python: pypy3
      env: TOXENV=pypy3

  allow_failures:
    - python: 3.10-dev

install:
  - pip install tox

script:
  - tox -- --verbose
